In [ ]:
# Load the Drive helper and mount
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
DATASET_PATH = f'/content/drive/MyDrive/lab2_kaggle/result{iter}_csv'

df_list = []
for iter in range(1, 43):
    df_list.append(pd.read_csv(f'/content/drive/MyDrive/lab2_kaggle/result{iter}_csv',header=None))

df = pd.concat(df_list)

In [ ]:
df.columns = ['emotion']
df = df.reset_index()
df

        index       emotion
0           0  anticipation
1           1           joy
2           2  anticipation
3           3  anticipation
4           4         trust
...       ...           ...
411967   1967           joy
411968   1968  anticipation
411969   1969       sadness
411970   1970         trust
411971   1971       sadness

[411972 rows x 2 columns]

In [ ]:
test_data = pd.read_csv('/content/drive/MyDrive/testing_csv')
test_data.set_index("id",inplace=True)
test_data

                                                       text
id
0x28b412  Confident of your obedience, I write to you, k...
0x2de201  "Trust is not the same as faith. A friend is s...
0x218443  When do you have enough ? When are you satisfi...
0x2939d5  God woke you up, now chase the day #GodsPlan #...
0x26289a  In these tough times, who do YOU turn to as yo...
...                                                     ...
0x2913b4  "For this is the message that ye heard from th...
0x2a980e  "There is a lad here, which hath five barley l...
0x316b80  When you buy the last 2 tickets remaining for ...
0x29d0cb  I swear all this hard work gone pay off one da...
0x2a6a4f  @Parcel2Go no card left when I wasn't in so I ...

[411972 rows x 1 columns]

In [ ]:
test_data = test_data.rename_axis('id').reset_index()

In [ ]:
test_data

              id                                               text
0       0x28b412  Confident of your obedience, I write to you, k...
1       0x2de201  "Trust is not the same as faith. A friend is s...
2       0x218443  When do you have enough ? When are you satisfi...
3       0x2939d5  God woke you up, now chase the day #GodsPlan #...
4       0x26289a  In these tough times, who do YOU turn to as yo...
...          ...                                                ...
411967  0x2913b4  "For this is the message that ye heard from th...
411968  0x2a980e  "There is a lad here, which hath five barley l...
411969  0x316b80  When you buy the last 2 tickets remaining for ...
411970  0x29d0cb  I swear all this hard work gone pay off one da...
411971  0x2a6a4f  @Parcel2Go no card left when I wasn't in so I ...

[411972 rows x 2 columns]

In [ ]:
merged_df = pd.concat([test_data, df], axis=1)

In [ ]:
merged_df = merged_df.drop(['text','index'],axis = 1)

In [ ]:
merged_df

              id       emotion
0       0x28b412  anticipation
1       0x2de201           joy
2       0x218443  anticipation
3       0x2939d5  anticipation
4       0x26289a         trust
...          ...           ...
411967  0x2913b4           joy
411968  0x2a980e  anticipation
411969  0x316b80       sadness
411970  0x29d0cb         trust
411971  0x2a6a4f       sadness

[411972 rows x 2 columns]

In [ ]:
## read data from google drive
DATASET_PATH = '/content/drive/MyDrive/submission.csv'

## get a sample to acelerate training 
merged_df.to_csv(DATASET_PATH,index = False)